---
# depth=1 causes "fatal: No names found, cannot describe anything." by "git describe"
- name: "Clone nadoka repository"
  git:
    dest: "{{ nadoka_nadoka }}"
    repo: https://github.com/nadoka/nadoka
  notify: restart nadoka service
- name: "Clone fprog nadoka plugins repository"
  git:
    dest: "{{ nadoka_fprog_plugins }}"
    repo: https://github.com/znz/fprog-nadoka-plugins
  notify: restart nadoka service
