---
# handlers file for znz.nadoka
- name: "Restart nadoka service"
  systemd:
    name: "nadoka@{{ item.service_name }}.service"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items: "{{ nadoka }}"
