#!/bin/sh
loguser=uucp
logdir="/var/log/runit/$(basename $(dirname $(pwd)))"
umask 027
if [ ! -d /var/log/runit ]; then
    mkdir -p /var/log/runit
    chown "$loguser:adm" /var/log/runit
fi
chpst -u "$loguser:adm" mkdir -p "$logdir"
cd "$logdir"
exec chpst -u "$loguser:adm" svlogd -tt "$logdir"
